# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/130wwHzSaomJvjwee5JeRyRBZ3B-FohNn
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/sample_data/train.csv")

# DataFrame
print("DataFrame Preview:")
print(df.head())

# Create Series objects
age_series = df["Age"]
fare_series = df["Fare"]
survived_series = df["Survived"]

print("\nAge Series Sample:")
print(age_series.head())

print("\nDataset Info:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe())

print("\nMissing Values:")
print(df.isnull().sum())

# Fill missing Age with mean
df["Age"].fillna(df["Age"].mean(), inplace=True)

# Fill missing Embarked with mode
df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)

# Drop Cabin column (too many missing values)
df.drop(columns=["Cabin"], inplace=True)

print("\nMissing Values After Cleaning:")
print(df.isnull().sum())

# Using loc (label based)
print("\nPassenger Details using loc:")
print(df.loc[0])

# Using iloc (position based)
print("\nFirst 5 Passengers using iloc:")
print(df.iloc[0:5])

# Extract specific columns
print("\nAge, Fare and Survival Status:")
print(df[["Age", "Fare", "Survived"]].head())

# Rename column
df.rename(columns={"Sex": "Gender"}, inplace=True)

# Pivot Table (Average Fare by Gender & Class)
pivot_table = df.pivot_table(values="Fare", index="Gender", columns="Pclass", aggfunc="mean")
print("\nPivot Table (Average Fare):")
print(pivot_table)

# Age > 30
age_above_30 = df[df["Age"] > 30]

# Fare > 50
fare_above_50 = df[df["Fare"] > 50]

# Female passengers who survived
female_survived = df[(df["Gender"] == "female") & (df["Survived"] == 1)]

print("\nFemale Survivors:")
print(female_survived.head())

# Sorting
print("\nSorted by Fare (Highest First):")
print(df.sort_values(by="Fare", ascending=False).head())

print("\nSorted by Age:")
print(df.sort_values(by="Age").head())

# Survival rate by Gender
survival_by_gender = df.groupby("Gender")["Survived"].mean()
print("\nSurvival Rate by Gender:")
print(survival_by_gender)

# Average Age by Passenger Class
avg_age_class = df.groupby("Pclass")["Age"].mean()
print("\nAverage Age by Passenger Class:")
print(avg_age_class)

# Survival count by Embarked location
survival_embarked = df.groupby("Embarked")["Survived"].sum()
print("\nSurvival Count by Embarked Location:")
print(survival_embarked)

# Create additional DataFrame (Class Category)
class_info = pd.DataFrame({
    "Pclass": [1, 2, 3],
    "Class_Type": ["Upper", "Middle", "Lower"]
})

# Merge
merged_df = pd.merge(df, class_info, on="Pclass")
print("\nMerged DataFrame Sample:")
print(merged_df.head())

# Concatenation Example
df_part1 = df.iloc[:400]
df_part2 = df.iloc[400:]

concatenated_df = pd.concat([df_part1, df_part2])
print("\nConcatenated DataFrame Shape:", concatenated_df.shape)

# Average age of survivors vs non-survivors
avg_age_survival = df.groupby("Survived")["Age"].mean()
print("\nAverage Age (0 = Not Survived, 1 = Survived):")
print(avg_age_survival)

# Highest and lowest fare
print("\nHighest Fare Paid:", df["Fare"].max())
print("Lowest Fare Paid:", df["Fare"].min())

# Survival percentage
survival_percentage = (df["Survived"].mean()) * 100
print("\nOverall Survival Percentage:", survival_percentage)

print("\nKey Insights:")
print("1. Females had a higher survival rate than males.")
print("2. First-class passengers had better survival chances.")
print("3. Higher fare passengers had better survival probability.")
print("4. Younger passengers had slightly better survival rates.")